ip: 192.168.94.147
password: raqFUHQ2
calibration:
  angle:
    # max = turn left, min = turn right
    max: 23
    mid: -9
    min: -24
    polarity: 1

  throttle:
    # max = reverse max speed, mid = zero speed, min = forward max speed
    max: 25
    mid: -12
    min: -47
    polarity: -1
    
